# Generated by Django 5.0.1 on 2024-01-05 10:08

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_note_shared_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='note',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='app_note_search__884e5e_gin'),
        ),
    ]
