# Generated by Django 5.0.1 on 2024-01-05 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_note_search_vector_note_app_note_search__884e5e_gin'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='note',
            name='app_note_search__884e5e_gin',
        ),
        migrations.RemoveField(
            model_name='note',
            name='search_vector',
        ),
    ]
