# Generated by Django 5.0.1 on 2024-01-05 14:18

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_note_app_note_search__884e5e_gin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='search_query',
            field=django.contrib.postgres.search.SearchQueryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
    ]
