# Generated by Django 5.0.1 on 2024-01-05 14:46

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_note_search_query_remove_note_search_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='search_query',
            field=django.contrib.postgres.search.SearchQueryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
    ]
