# Generated by Django 5.0.1 on 2024-01-05 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_note_search_query_note_search_vector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='search_query',
        ),
        migrations.RemoveField(
            model_name='note',
            name='search_vector',
        ),
    ]
